[package]
name = "day11"
version = "0.1.0"
authors = ["Tim Roberts <timr@probo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
lazy_static = "1.4.0"
